### ISSUE TITLE
shard のインストールコマンドについて

### ISSUE THREAD

**Issue by arcage** [crystal-jp/introducing-crystal#25]
shard のインストールには現状 `shard install` と `crystal deps` の2パターンが利用できます。

Shards の章では後者を選択しましたが，それぞれの章で `shard install` と `crystal deps` が混在していると読者の混乱を招きそうです。

可能であればどちらかに統一すべきではないかと思いますがいかがでしょう？
また，もし統一するとしたらどちらを採用しますか？

ちなみに，私が後者を選択したのは

- 読者に提示するコマンドの数は少ない方が良いのではないか
    `crystal` コマンドはどうしても出てくるので

- Crystal コンパイラのサブコマンドとして実行できることで，標準のパッケージマネージャである点が強調されるのではないか

といった辺りが理由でした。

**Comment by MakeNowJust** [comment]
`shards` 以外使わないでください。`crystal deps` は master だと既に削除されています。 https://github.com/crystal-lang/crystal/pull/5544

**Comment by arcage** [comment]
それはチェックできてませんでした。
了解です。
その方向で修正します。

**Comment by MakeNowJust** [comment]
`crystal deps`はもう無いみたいなのでクローズします。
