### ISSUE TITLE
著者紹介

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-jp/introducing-crystal#50]
@crystal-jp/introducing-crystal 

著者紹介のページを作りたいので、このissueに下記の内容をコメントしてもらいたいです。

  - 本に載せたい名前
  - GitHubのアカウント名
  - Twitterのアカウント名
  - 自己紹介(100字くらい？)

よろしくお願いします。

**Comment by at-grandpa** [comment]
- 本に載せたい名前
  - @at_grandpa
- GitHubのアカウント名
  - at-grandpa （ハイフンになってます）
- Twitterのアカウント名
  - @at_grandpa
- 自己紹介(100字くらい？)
  - Crystalと出会い、衝撃を受けて好きになり、コードを書いたり活動をしていたところ、このような執筆の機会をいただきました。ありがとうございます。Crystal言語はとてもおもしろいのでぜひ触れてみてください。 Happy crystalling!!

以上でお願いしますー

**Comment by arcage** [comment]
- 本に載せたい名前
    - AKJ
- GitHubのアカウント名
    - arcage
- Twitterのアカウント名
    - @arcage
- 自己紹介(100字くらい？)
    - 地方でシスアド業の傍ら、趣味でコードを書いてます。常々型に厳格な Ruby が欲しいと思っていたところに Crystal と出会い、以来 Crystal にどっぷりとハマっています。

でお願いします。

**Comment by MakeNowJust** [comment]
そろそろ言い出した本人が書かないとまずいので。

* 本に載せたい名前
  - MakeNowJust
* GitHubのアカウント名
  - MakeNowJust
* Twitterのアカウント名
  - make_now_just
* 自己紹介(100字くらい？)
  - 仕事でTypeScriptを書く傍らで、趣味で Crystal のコンパイラやフォーマッタにコントリビュートしています。Crystal のコンパイラは Crystal 自身で書かれていて、他の C 言語などで書かれたコンパイラよりはコントリビュートの障壁は低いかと思います。 Crystal に興味を持ったらコンパイラや標準ライブラリのコードを読んでみると良いかもしれません。

**Comment by msky026** [comment]
- 本に載せたい名前
      - msky
  - GitHubのアカウント名
      - @msky026
  - Twitterのアカウント名
      - @msky026
  - 自己紹介(100字くらい？)
      - 本業はスマホゲーの人。RubyやUnityなど業務や趣味で使ってたりします。CrystalはビルドできるRubyがあったらいいなと思ってた時に存在を知り、そのタイミングで第2回Crystal勉強会が開催されてたのでそのままどっぷりと。

**Comment by MakeNowJust** [comment]
本文に追加したのでクローズします。
