### ISSUE TITLE
`crystal init`した際のテンプレートが変わったので、サンプルプロジェクトを更新する

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-jp/introducing-crystal#56]
Related: crystal-lang/crystal#6942

次バージョンのCrystalで、`crystal init`した際のテンプレートが一部変更されたので記事中で参照しているプロジェクトもそれに合わせて更新したいです。

合わせて、単に`shards`コマンドで依存関係をインストールするように指示していたのが`shards install`コマンドを使うように変わったので、記事でもそちらに揃えようかと思っています。

/cc @at-grandpa @msky026 @arcage

**Comment by arcage** [comment]
了解です。
0.27.0が公開されたら、変更箇所を確認して反映させるようにします。

**Comment by arcage** [comment]
0.27.0対応の修正はmasterからブランチ切ってPR出せば良い感じですか？

**Comment by MakeNowJust** [comment]
`master`から切ってもらって大丈夫です。

あと、各人の記事を個別に修正するより、全部まとめて直したいので、可能なら全員分やってもらえると嬉しいです。(難しいなら自分の分だけで大丈夫です)
