### ISSUE TITLE
Crystal　のバージョンの統一

### ISSUE THREAD

**Issue by 5t111111** [crystal-jp/introducing-crystal#9]
動作確認や `make test` で使うのも含め、現時点の最新バージョンの `0.24.1` で統一する方針でよいですか？

本で使われているバージョンに関する記載が第1章の項目に入る予定です。

> この本がどのバージョンのCrystalを前提にしているかもここに入る。

**Comment by MakeNowJust** [comment]
そのつもりです。CIのCrystalのバージョンが何だったか自信がないのであとで確認しておきます。

**Comment by 5t111111** [comment]
ありがとうございます。ではそのつもりでいます！

**Comment by MakeNowJust** [comment]
0.24.2だあああああ┗(^o^)┛ｗｗｗｗｗｗ┏(^o^)┓ﾄﾞｺﾄﾞｺﾄﾞｺﾄﾞｺｗｗｗｗｗｗｗ

https://github.com/crystal-lang/crystal/releases/tag/0.24.2

**Comment by MakeNowJust** [comment]
うーん、どうしよう‥‥

**Comment by 5t111111** [comment]
Oh...まあどうせ販売するときにどうなってるかわかんないから慌てて更新する必要もないかなと思いつつ、でも changelog の内容も多くないから影響ないだろうし `0.24.2` でいきますかね。

とりあえず何か不都合がなければ僕はそのつもりでいます。

**Comment by MakeNowJust** [comment]
ボクもそのつもりです。CIの方はなるべく早めにアップデートします

**Comment by MakeNowJust** [comment]
まだAlpineの0.24.2が出回ってないのでもう少し待ちます https://github.com/ysbaddaden/crystal-alpine

**Comment by MakeNowJust** [comment]
AlpineでCrystalの0.24.2が動かせそうだったのでバージョンを上げておきました。

何も考えずにlatestで上げてしまったので次のCIからバージョンが上がります。（次があったらちゃんとタグ付けします）
